version: 3

tasks:
  lint:
    cmds:
      - golangci-lint run -c ./golangci.yml ./...

  test:
    cmds:
      - go test -v `go list ./... | grep -v -e './examples' -e './test'` --cover
  test:report:
    cmds:
      - go test -v `go list ./... | grep -v -e './examples' -e './test'` --coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  run:example:base:
    cmds:
      - go run main.go serve
    dir: examples/base

  run:example:react:
    cmds:
      - cd ./tg_webapp
      - npm i
      - npm run build
      - cd ..
      - go run main.go serve
    dir: examples/webapp-react

  run:test-server:
    cmds:
      - go run main.go serve
    dir: test

  # Generate docs
  # Require gomarkdoc (https://github.com/princjef/gomarkdoc)
  docs:
    cmds:
      - go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
      - gomarkdoc -o README.md -e .